### ISSUE TITLE
Status: Submission failed. Possible reasons: reCAPTCHA validation failed, invalid email address, input file invalid or exceeds size limit. Please check and re-try- if issue remains, please contact us.

### ISSUE THREAD

**Issue by SunTongtongtong** [Cuberick-Orion/CIRR#15]
The problem keeps popping up. I use the same email and the same submission file. But it succeeds randomly, is it possible to solve this problem?

**Comment by Cuberick-Orion** [comment]
Hi,

Thank you for raising this concern.

We have just reply to your email.

**Comment by Cuberick-Orion** [comment]
*To make a note on this issue:*

If the submission does succeed, then the server is likely okay. I can only suspect that the "on and off" behaviour is caused by Google's reCAPTCHA -- as in, it might be blocking some of the submissions because it thinks they are malicious (it is currently recording a ~50% suspicious activity rate, which seems a bit high indeed).

Unfortunately, we have no control over how reCAPTCHA works, and for obvious reasons, we prefer not to turn it off for the entire site.
We do apologise for the inconvenience.

We could only suggest perhaps switching the device/s and IP address used for the submission, and possibly avoiding submitting multiple times in a very short period.

Best,
David.

**Comment by Cuberick-Orion** [comment]
We have now replaced reCAPTCHA with hCaptcha and it should be less sensitive.
